# Generated by Django 4.0 on 2022-01-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_course_work_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='EXHIBITION_ID',
            new_name='EXCURSION_ID',
        ),
    ]
